// All Features Data
export const allFeatures = [
  // Money Transfer Features
  {
    category: 'transfer',
    title: 'Instant Money Transfer',
    description: 'Send money to any user instantly using mobile number',
    icon: '⚡',
    color: 'from-blue-500 to-cyan-500',
    benefits: ['Instant transfer', 'No hidden fees', '24/7 availability'],
  },
                                                                                                                                               
  {
    category: 'transfer',
    title: 'International Remittance',
    description: 'Send money abroad with competitive exchange rates',
    icon: '🌍',
    color: 'from-green-500 to-emerald-500',
    benefits: ['Global reach', 'Best rates', 'Secure transfer'],
  },
  {
    category: 'transfer',
    title: 'Bulk Transfers',
    description: 'Send money to multiple recipients at once for businesses',
    icon: '📊',
    color: 'from-purple-500 to-violet-500',
    benefits: ['Bulk processing', 'CSV upload', 'Business tools'],
  },
  {
    category: 'cash_in',
    title: 'Cash In',
    description: 'Agent can add money to user wallet',
    icon: '💸',
    color: 'from-purple-500 to-violet-500',
    benefits: ['Commission', 'No hidden fees', 'Instant transfer'],
  },
  {
    category: 'cash_out',
    title: 'Cash Out',
    description: 'Agent withdraw money from user wallet',
    icon: '📥',
    color: 'from-purple-500 to-violet-500',
    benefits: ['Instant transfer', 'Commission', 'No hidden fees'],
  },
  {
    category: 'send_money',
    title: 'Send Money',
    description: 'Send money to multiple recipients at once for businesses',
    icon: '📱',
    color: 'from-purple-500 to-violet-500',
    benefits: ['Instant transfer', 'Free send upto 100 tk', 'Limited amount'],
  },
  {
    category: 'withdraw',
    title: 'Withdraw',
    description: 'Withdraw money from user wallet',
    icon: '🏧',
    color: 'from-purple-500 to-violet-500',
    benefits: ['Instant transfer', 'No hidden fees', 'Limited'],
  },
  {
    category: 'deposit',
    title: 'Deposit',
    description: 'Deposit money to user wallet',
    icon: '💰',
    color: 'from-purple-500 to-violet-500',
    benefits: ['Instant transfer', 'No hidden fees', 'Limited'],
  },
  // Security Features
  {
    category: 'security',
    title: 'Biometric Security',
    description: 'Secure your account with fingerprint and face recognition',
    icon: '👆',
    color: 'from-indigo-500 to-purple-500',
    benefits: ['Fingerprint', 'Face ID', 'Voice recognition'],
  },
  {
    category: 'security',
    title: 'Transaction Limits',
    description: 'Set daily and monthly transaction limits for safety',
    icon: '🛡️',
    color: 'from-gray-600 to-gray-800',
    benefits: ['Custom limits', 'Real-time alerts', 'Fraud protection'],
  },
  {
    category: 'security',
    title: 'Bcrypt Password Authentication',
    description: 'Extra layer of security with Hashing PIN',
    icon: '🔐',
    color: 'from-yellow-500 to-orange-500',
    benefits: ['Hashing PIN', 'Using Strong Password', 'User Authentication'],
  },
];
